variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

# Stage: build
##############################################################################

image:
  stage: build
  script:
    - make upload
  tags:
    - shell
    - linux

# Stage: deploy
##############################################################################

deploy:kubernetes:
  stage: deploy
  variables:
    KUBECONFIG: /root/.kube/config
  image: registry.git.rwth-aachen.de/acs/cloud/kubernetes/deployment
  before_script:
    - mkdir -p $(dirname ${KUBECONFIG})
    - echo "${KUBECONFIG_ENCODED}" | base64 -d > ${KUBECONFIG}
    - kubectl version
  script:
    - make deploy
  tags:
    - docker
