variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  RSYNC_OPTS: --recursive --ignore-missing-args --copy-links --chown $DEPLOY_USER:$DEPLOY_USER

stages:
  - prepare
  - build
  - deploy

# Stage: prepare
##############################################################################

# Build docker image which is used to build & test VILLASnode
docker:
  stage: prepare
  script:
    - docker build -t villas/documentation-creator .
  tags:
    - shell
    - linux
  only:

# Stage: build
##############################################################################

build:
  stage: build
  artifacts:
    name: "${CI_PROJECT_NAME}-doc-${CI_BUILD_REF}"
    paths:
      - html/
  script:
    - make
  tags:
    - docker
  image: villas/documentation-creator

# Stage: deploy
##############################################################################

upload:
  stage: deploy
  script:
    - make deploy
  dependencies:
    - build
  only:
    - master
  tags:
    - shell