influxdb:
  image: influxdb:1.7.10
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
    - "8089:8089/udp"
  environment:
    - INFLUXDB_DATA_ENGINE=tsm1
    - INFLUXDB_REPORTING_DISABLED=false
    - INFLUXDB_DB=villas
    - INFLUXDB_ADMIN_USER=admin
    - INFLUXDB_ADMIN_PASSWORD=admin
    - INFLUXDB_UDP_ENABLED=true
    - INFLUXDB_UDP_DATABASE=villas

grafana:
  image: grafana/grafana:6.6.2
  container_name: grafana
  ports:
    - "3000:3000"
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
  links:
    - influxdb
